-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 02:00:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Forum
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Forum` ;

-- -----------------------------------------------------
-- Schema Forum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Forum` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Forum` ;

-- -----------------------------------------------------
-- Table `categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categories` (
  `idcategories` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategories`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `comment` (
  `commentid` INT NOT NULL,
  `content` VARCHAR(45) NULL,
  `comment-at` DATETIME NULL,
  `post_postid` INT NOT NULL,
  `user_userid` INT NOT NULL,
  PRIMARY KEY (`commentid`, `post_postid`, `user_userid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dislike`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dislike` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dislike` (
  `dislikeid` INT NOT NULL,
  `dislike-at` DATE NULL,
  `user_userid` INT NOT NULL,
  `post_postid` INT NOT NULL,
  PRIMARY KEY (`dislikeid`, `user_userid`, `post_postid`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `dislikeid_UNIQUE` ON `dislike` (`dislikeid` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `like` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `like` (
  `likeid` INT NOT NULL,
  `like-at` DATETIME NULL,
  `post_postid` INT NOT NULL,
  `user_userid` INT NOT NULL,
  PRIMARY KEY (`likeid`, `post_postid`, `user_userid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `post` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `post` (
  `postid` INT NOT NULL,
  `image` INT NULL,
  `contant` INT NULL,
  `post-at` DATETIME NOT NULL,
  `user_userid` INT NOT NULL,
  PRIMARY KEY (`postid`, `user_userid`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `postid_UNIQUE` ON `post` (`postid` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `post_has_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `post_has_categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `post_has_categories` (
  `post_postid` INT NOT NULL,
  `post_user_userid` INT NOT NULL,
  `categories_idcategories` INT NOT NULL,
  PRIMARY KEY (`post_postid`, `post_user_userid`, `categories_idcategories`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `session` (
  `sessionid` INT NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  PRIMARY KEY (`sessionid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `userid` INT NOT NULL,
  `F-name`  NOT NULL,
  `L-name` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `current_session` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`userid`, `current_session`),
  FOREIGN KEY (`role_id`) REFERENCES `user_roles`(`roleid`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Username_UNIQUE` ON `user` (`Username` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `userid_UNIQUE` ON `user` (`userid` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_roles` (
  `roleid` INT NOT NULL,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`roleid`))
ENGINE = InnoDB;

SHOW WARNINGS;
INSERT INTO `user_roles` (`roleid`, `role_name`) VALUES (1, 'admin'), (2, 'moderator'), (3, 'normal_user');

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `friends` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `friends` (
  `user_userid` INT NOT NULL,
  `friend_userid` INT NOT NULL,
  PRIMARY KEY (`user_userid`, `friend_userid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `followers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `followers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `followers` (
  `user_userid` INT NOT NULL,
  `follower_userid` INT NOT NULL,
  PRIMARY KEY (`user_userid`, `follower_userid`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `notifications` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `notifications` (
  `notificationid` INT NOT NULL,
  `user_userid` INT NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`notificationid`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;